INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (1, 'Manager', 'Manager', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (2, 'HR & Admin Executive', 'HR & Admin', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (3, 'Production Manager', 'Prod Manager', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (4, 'Cold Storage Manager', 'C.S. Manager', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (5, 'Plant Engineer', 'Plant Engineer', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (6, 'IT Operator', 'IT Operator', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (7, 'Junior Executive', 'Jr. Executive', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (8, 'Supervisor', 'Supervisor', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (9, 'Cold Storage Supervisor', 'C.S. Supervisor', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (10, 'Foreman', 'Foreman', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (11, 'Quality Assurance Manager', 'QA Manager', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (12, 'Microbiologist', 'Microbiologist', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (13, 'QA Executive', 'QA Executive', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (14, 'Worker', 'Worker', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (15, 'Helper', 'Helper', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (16, 'Electrician', 'Electrician', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (17, 'Operator', 'Operator', null);
