INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (1, 'Manager', 'Manager', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (2, 'Executive', 'Executive', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (3, 'HR & Admin', 'HR & Admin', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (4, 'Junior Executive', 'Jr Executive', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (5, 'Production Manager', 'Production Manager', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (6, 'Cold Storage Manager', 'Cold Storage Manager', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (7, 'Cold Storage Supervisor', 'Cold Storage Supervisor', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (8, 'Quality Assurance Manager', 'Quality Assurance Manager', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (9, 'Microbiologist', 'Microbiologist', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (10, 'Plant Engineer', 'Plant Engineer', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (11, 'HR & Admin Executive', 'HR & Admin Executive', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (12, 'IT Operator', 'IT Operator', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (13, 'Shift In Charge', 'Shift In Charge', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (14, 'Worker', 'Worker', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (15, 'Helper', 'Helper', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (16, 'Foreman', 'Foreman', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (17, 'Electrecian', 'Electrecian', null);
INSERT INTO soptorshi.designation (id, name, short_name, description) VALUES (18, 'Operator', 'Operator', null);
