INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (1, 'Assets', null, 'RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (2, 'Fixed Assets', 1, 'NOT_RESERVED', 'admin', '2019-10-22');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (3, 'Current Assets', 1, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (4, 'Sundry Deptors', 3, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (5, 'Stock In Hand', 3, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (6, 'Bank Accounts', 3, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (7, 'Loans and Advances', 3, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (8, 'Funds & Liabilities', null, 'RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (9, 'Current Liabilities', 8, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (10, 'Secured Loans', 8, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (11, 'Unsecured Loans', 8, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (12, 'Sundry Creditors', 9, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (13, 'Income (Revenue)', null, 'RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (14, 'Sales Account', 13, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (15, 'Other Income', 13, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (16, 'Expenses', null, 'RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (17, 'Direct Expense', 16, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (18, 'Indirect Expenses', 16, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (19, 'Recurring Expenses', 18, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (20, 'Purchase Account', 17, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (21, 'Asset Depreciation', 16, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (22, 'Advances of Tax & VAT', 3, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (23, 'Modvat Receivable', 22, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (24, 'Consumption', 16, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (25, 'Excise Paid', 17, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (26, 'Cash In Hand', 3, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (27, 'Excise Duty Recovery', 15, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (28, 'Security Deposit', 9, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (29, 'Excise Payable', 17, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (30, 'Tax & Vat Payable', 9, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (31, 'Commission Earned', 13, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (32, 'IT Equipments', 2, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (33, 'Investment', 1, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (34, 'Furniture & Fixture', 2, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (35, 'Building', 2, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (36, 'Vahicles', 2, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (37, 'Office Equipment', 2, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (38, 'Electrical & Electronics Equip', 2, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (39, 'Share Capital', 8, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (40, 'Accumulated Depreciation', 8, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (41, 'Inter Company Funding', 8, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (42, 'Admin Expenses', 18, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (43, 'Marketing & Sales Expenses', 18, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (44, 'Financial Expenses', 18, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (45, 'Operating Income', 13, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (46, 'Loan Receiver', 3, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (47, 'Funds', 8, 'NOT_RESERVED', 'admin', '2019-10-21');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (48, 'Accumulated Depreciation', 47, 'NOT_RESERVED', 'admin', '2019-10-22');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (49, 'Capital Account', 8, 'NOT_RESERVED', 'admin', '2019-10-22');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (50, 'Paid Up Capital', 8, 'NOT_RESERVED', 'admin', '2019-10-22');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (51, 'Retained Earnings', 47, 'NOT_RESERVED', 'admin', '2019-10-23');
