INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (1, 'Assets', null, 'RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (2, 'Fixed Assets', 1, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (3, 'Current Assets', 1, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (4, 'Sundry Deptors', 3, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (5, 'Stock In Hand', 3, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (6, 'Bank Accounts', 3, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (7, 'Loans and Advances', 3, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (8, 'Liabilities', null, 'RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (9, 'Current Liabilities', 8, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (10, 'Secured Loans', 8, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (11, 'Unsecured Loans', 8, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (12, 'Sundry Creditors', 9, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (13, 'Income (Revenue)', null, 'RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (14, 'Sales Account', 13, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (15, 'Other Income', 13, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (16, 'Expenses', null, 'RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (17, 'Direct Expense', 16, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (18, 'Indirect Expenses', 16, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (19, 'Recurring Expenses', 18, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (20, 'Purchase Account', 17, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (21, 'Asset Depreciation', 16, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (22, 'Advances of Tax & VAT', 3, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (23, 'Modvat Receivable', 22, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (24, 'Consumption', 16, 'NOT_RESERVED', 'admin', '2019-09-30');
INSERT INTO soptorshi.mst_group (id, name, main_group, reserved_flag, modified_by, modified_on) VALUES (25, 'Excise Paid', 17, 'NOT_RESERVED', 'admin', '2019-09-30');
