package org.soptorshi.domain.enumeration;

/**
 * The AllowanceType enumeration.
 */
public enum AllowanceType {
    HOUSE_RENT, MEDICAL_ALLOWANCE, FESTIVAL_BONUS, OVERTIME_ALLOWANCE, FOOD_ALLOWANCE, DRIVER_ALLOWANCE, FUEL_LUB_ALLOWANCE, TRAVEL_ALLOWANCE, CONV_ALLOWANCE, MOBILE_ALLOWANCE, ARREAR_ALLOWANCE, OTHER_ALLOWANCE
}
