package org.soptorshi.domain.enumeration;

/**
 * The GroupType enumeration.
 */
public enum GroupType {
    ASSETS, LIABILITIES, EQUITIES, INCOME, EXPENSES, BANK_ACCOUNTS, CASH_IN_HAND, SUNDRY_DEBTOR, SUNDRY_CREDITOR, CURRENT_LIABILITIES, CURRENT_ASSETS, FIXED_ASSETS, LOAN, SHARE_CAPITAL, DEPRECIATION
}
