package org.soptorshi.domain.enumeration;

/**
 * The RequisitionStatus enumeration.
 */
public enum RequisitionStatus {
    REJECTED_BY_HEAD, FORWARDED_BY_HEAD, FORWARDED_BY_PURCHASE_COMMITTEE, REJECTED_BY_PURCHASE_COMMITTEE, CORRECTION_REQUEST_BY_PURCHASE_COMMITTEE, APPROVED_BY_CFO, REJECTED_BY_CFO, CORRECTION_REQUEST_BY_CFO, CLOSED_BY_CFO
}
