package org.soptorshi.domain.enumeration;

/**
 * The RequisitionStatus enumeration.
 */
public enum RequisitionStatus {
    WAITING_FOR_HEADS_APPROVAL, REJECTED_BY_HEAD, FORWARDED_BY_HEAD, FORWARDED_BY_PURCHASE_COMMITTEE, REJECTED_BY_PURCHASE_COMMITTEE, MODIFICATION_REQUEST_BY_PURCHASE_COMMITTEE, APPROVED_BY_CFO, REJECTED_BY_CFO, MODIFICATION_REQUEST_BY_CFO, RECEIVED_BY_REQUISIONER, RECEIVED_VERIFIED_BY_HEAD, CLOSED_BY_CFO
}
