version: '2'
services:
    soptorshi-app:
        image: soptorshi
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://soptorshi-mysql:3306/soptorshi?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://soptorshi-elasticsearch:9200
        ports:
            - 8080:8080
    soptorshi-mysql:
        extends:
            file: mysql.yml
            service: soptorshi-mysql
    soptorshi-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: soptorshi-elasticsearch
